In [1]:
import numpy as np
import pandas as pd

In [2]:
import os
os.getcwd()

'C:\\Users\\KIIT\\Desktop\\Machine Learning Project\\Movie Recommender System'

In [3]:
os.chdir(os.getcwd())

In [4]:
movies = pd.read_csv("tmdb_5000_movies.csv")

In [5]:
credits = pd.read_csv("tmdb_5000_credits.csv")

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
movies = movies.merge(credits,on='title')

In [8]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [10]:
# lets take all the columns that we need
#genres, id,title,overview cast crew

In [11]:
movies = movies[['movie_id','genres', 'title' , 'overview', 'cast' ,'crew' ,'keywords']]

In [12]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [13]:
movies.isnull().sum()

movie_id    0
genres      0
title       0
overview    3
cast        0
crew        0
keywords    0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.duplicated().sum()

0

In [16]:
movies['genres'][0]
import ast

In [17]:
def convert(obj):
    list=[]
    for i in ast.literal_eval(obj):
        list.append(i['name'])
    return list

In [18]:
movies['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4806, dtype: object

In [19]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [20]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [21]:
# picking top 3 cast names

In [22]:
def convert3(obj):
    l = []
    cnt = 0
    for i in ast.literal_eval(obj):
        if cnt!=3:
            l.append(i['name'])
            cnt+=1
        else:
            break
    return l

In [23]:
movies['cast'] = movies['cast'].apply(convert3)

In [24]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [25]:
# getting only director from crew

In [26]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [27]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [28]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [29]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [30]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [31]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [32]:
# concatination of space separated words

In [33]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [34]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [35]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [36]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords
0,19995,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,..."
1,285,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,..."
2,206647,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,..."
3,49026,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,..."
4,49529,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,..."

In [37]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [38]:
movies.head()

,movie_id,genres,title,overview,cast,crew,keywords,tags
0,19995,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[Following, the, death, of, District, Attorney..."
4,49529,"[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[John, Carter, is, a, war-weary,, former, mili..."

In [39]:
new_df = movies[['movie_id','title','tags']]

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
new_df['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'd',
 'v',
 'e',
 'n',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'F',
 'a',
 'n',
 't',
 'a',
 's',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '8',
 '7',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 '',
 'F',
 'i',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ']',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'u',
 'l',
 't',
 'u',
 'r',
 'e',
 '',
 'c',
 'l',
 'a',
 's',
 'h',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '9',
 '6',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '6',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'c',
 'o',
 'l',
 'o',
 'n',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '6',
 '7',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'c',
 'i',
 'e',
 't',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '8',
 '0',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 't',
 'r',
 'a',
 'v',
 'e',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '6',
 '8',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'i',
 's',
 't',
 'i',
 'c',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '4',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'r',
 'o',
 'm',
 'a',
 'n',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '8',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '9',
 '5',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '4',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 't',
 'r',
 'i',
 'b',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '5',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '',
 'p',
 'l',
 'a',
 'n',
 'e',
 't',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '9',
 '8',
 '7',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'g',
 'i',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '1',
 '3',
 '9',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'a',
 'r',
 'i',
 'n',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '3',
 '0',
 '6',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'l',
 'd',
 'i',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '4',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'b',
 'a',
 't',
 't',
 'l',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '7',
 '2',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'l',
 'o',
 'v',
 'e',
 '',
 'a',
 'f',
 'f',
 'a',
 'i',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '6',
 '5',
 '4',
 '3',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'n',
 't',
 'i',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '9',
 '3',
 '5',
 '5',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'p',
 'o',
 'w',
 'e',
 'r',
 '',
 'r',
 'e',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '6',
 '6',
 '9',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'i',
 'n',
 'd',
 '',
 'a',
 'n',
 'd',
 '',
 's',
 'o',
 'u',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '9',
 '7',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 '3',
 'd',
 '"',
 '}',
 ']',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [42]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\KIIT\AppData\Local\Temp\ipykernel_15024\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [43]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " S c i e n c e  F i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [44]:
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bondâ€™s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [45]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. [ { " i d " :  2 8 ,  " n a m e " :  " A c t i o n " } ,  { " i d " :  1 2 ,  " n a m e " :  " A d v e n t u r e " } ,  { " i d " :  1 4 ,  " n a m e " :  " F a n t a s y " } ,  { " i d " :  8 7 8 ,  " n a m e " :  " S c i e n c e  F i c t i o n " } ] [ { " i d " :  1 4 6 3 ,  " n a m e " :  " c u l t u r e  c l a s h " } ,  { " i d " :  2 9 6 4 ,  " n a m e " :  " f u t u r e " } ,  { " i d " :  3 3 8 6 ,  " n a m e " :  " s p a c e  w a r " } ,  { " i d " :  3 3 8 8 ,  " n a m e " :  " s p a c e  c o l o n y " } ,  { " i d " :  3 6 7 9 ,  " n a m e " :  " s o c i e t y " } ,  { " i d " :  3 8 0 1 ,  " n a m e " :  " s p a c e  t r a v e l " } ,  { " i d " :  9 6 8 5 ,  " n a m e " :  " f u t u r i s t i c " } ,  { " i d " :  9 8 4 0 ,  " n a m e " :  " r o m a n c e " } ,  { " i d " :  9 8 8 2 ,  " n a m e " :  " s p a c e " } ,  { " i d " :  9 9 5 1 ,  " n a m e " :  " a l i e n " } ,  { " i d " :  1 0 1 4 8 ,  " n a m e " :  " t r i b e " } ,  { " i d " :  1 0 1 5 8 ,  " n a m e " :  " a l i e n  p l a n e t " } ,  { " i d " :  1 0 9 8 7 ,  " n a m e " :  " c g i " } ,  { " i d " :  1 1 3 9 9 ,  " n a m e " :  " m a r i n e " } ,  { " i d " :  1 3 0 6 5 ,  " n a m e " :  " s o l d i e r " } ,  { " i d " :  1 4 6 4 3 ,  " n a m e " :  " b a t t l e " } ,  { " i d " :  1 4 7 2 0 ,  " n a m e " :  " l o v e  a f f a i r " } ,  { " i d " :  1 6 5 4 3 1 ,  " n a m e " :  " a n t i  w a r " } ,  { " i d " :  1 9 3 5 5 4 ,  " n a m e " :  " p o w e r  r e l a t i o n s " } ,  { " i d " :  2 0 6 6 9 0 ,  " n a m e " :  " m i n d  a n d  s o u l " } ,  { " i d " :  2 0 9 7 1 4 ,  " n a m e " :  " 3 d " } ] SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [46]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [47]:
import nltk
from nltk.stem.porter import PorterStemmer

In [48]:
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv = CountVectorizer(max_features = 5000,stop_words='english')

In [51]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [52]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
len(cv.get_feature_names_out())

5000

In [54]:
ps.stem('loving')

'love'

In [55]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_15024\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [56]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity = cosine_similarity(vectors)

In [59]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.04225771, 0.        ,
       0.        ])

In [60]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [61]:
recommend('Batman Begins')

The Dark Knight Rises
Raising Helen
The Dark Knight
Synecdoche, New York
Batman

In [62]:
import pickle

In [63]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [64]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [65]:
pickle.dump(similarity,open('similarity.pkl','wb'))